version: "3.0"
services:
  nginx:
    build: .docker/nginx
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - php7
    volumes:
      - .:/app
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  php7:
    build: .docker/php7
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
